"""Typed model of the Kubernetes objects Clavure reasons about.

Only the subset of Kubernetes needed for L3/L4 NetworkPolicy analysis is
modelled. Everything the parser cannot represent faithfully is recorded as an
:class:`UnsupportedFeature` instead of being dropped silently.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Verdict(StrEnum):
    """Outcome of evaluating one connection against the modelled semantics."""

    ALLOWED = "ALLOWED"
    BLOCKED = "BLOCKED"
    # The model cannot decide (e.g. ipBlock vs pod IP, unknown namespace labels).
    UNKNOWN = "UNKNOWN"
    # Objects or features outside the supported model may influence the result.
    UNSUPPORTED = "UNSUPPORTED"


class Direction(StrEnum):
    INGRESS = "Ingress"
    EGRESS = "Egress"


class SourceRef(BaseModel):
    """Where an object came from (file + document index, or the live cluster)."""

    model_config = ConfigDict(frozen=True)

    origin: Literal["manifest", "live-cluster", "generated"] = "manifest"
    path: str | None = None
    document: int | None = None

    def describe(self) -> str:
        if self.origin == "manifest":
            return f"{self.path}#{self.document}"
        if self.origin == "live-cluster":
            return "live cluster (not in manifests)"
        return "generated by Clavure"


class LabelSelectorRequirement(BaseModel):
    model_config = ConfigDict(frozen=True)

    key: str
    operator: Literal["In", "NotIn", "Exists", "DoesNotExist"]
    values: tuple[str, ...] = ()


class LabelSelector(BaseModel):
    """A Kubernetes label selector. An empty selector matches everything."""

    model_config = ConfigDict(frozen=True)

    match_labels: tuple[tuple[str, str], ...] = ()
    match_expressions: tuple[LabelSelectorRequirement, ...] = ()

    @classmethod
    def of(cls, labels: dict[str, str] | None = None, expressions=()) -> LabelSelector:
        return cls(
            match_labels=tuple(sorted((labels or {}).items())),
            match_expressions=tuple(expressions),
        )

    @property
    def is_empty(self) -> bool:
        return not self.match_labels and not self.match_expressions

    def labels_dict(self) -> dict[str, str]:
        return dict(self.match_labels)

    def matches(self, labels: dict[str, str]) -> bool:
        for key, value in self.match_labels:
            if labels.get(key) != value:
                return False
        for req in self.match_expressions:
            present = req.key in labels
            if req.operator == "In":
                if not present or labels[req.key] not in req.values:
                    return False
            elif req.operator == "NotIn":
                if present and labels[req.key] in req.values:
                    return False
            elif req.operator == "Exists":
                if not present:
                    return False
            elif req.operator == "DoesNotExist" and present:
                return False
        return True

    def referenced_keys(self) -> set[str]:
        return {k for k, _ in self.match_labels} | {e.key for e in self.match_expressions}

    def to_k8s(self) -> dict:
        out: dict = {}
        if self.match_labels:
            out["matchLabels"] = dict(self.match_labels)
        if self.match_expressions:
            exprs = []
            for e in self.match_expressions:
                item: dict = {"key": e.key, "operator": e.operator}
                if e.operator in ("In", "NotIn"):
                    item["values"] = list(e.values)
                exprs.append(item)
            out["matchExpressions"] = exprs
        return out

    def describe(self) -> str:
        if self.is_empty:
            return "{} (all)"
        parts = [f"{k}={v}" for k, v in self.match_labels]
        for e in self.match_expressions:
            if e.operator in ("In", "NotIn"):
                parts.append(f"{e.key} {e.operator} ({','.join(e.values)})")
            else:
                parts.append(f"{e.operator}({e.key})")
        return ", ".join(parts)


class IPBlock(BaseModel):
    model_config = ConfigDict(frozen=True)

    cidr: str
    except_: tuple[str, ...] = ()


class PolicyPeer(BaseModel):
    """One element of a rule's ``from``/``to`` list.

    ``pod_selector is None`` and ``namespace_selector is None`` mean the field
    was absent, which is semantically different from an empty selector.
    """

    model_config = ConfigDict(frozen=True)

    pod_selector: LabelSelector | None = None
    namespace_selector: LabelSelector | None = None
    ip_block: IPBlock | None = None

    def to_k8s(self) -> dict:
        out: dict = {}
        if self.pod_selector is not None:
            out["podSelector"] = self.pod_selector.to_k8s()
        if self.namespace_selector is not None:
            out["namespaceSelector"] = self.namespace_selector.to_k8s()
        if self.ip_block is not None:
            block: dict = {"cidr": self.ip_block.cidr}
            if self.ip_block.except_:
                block["except"] = list(self.ip_block.except_)
            out["ipBlock"] = block
        return out

    def describe(self) -> str:
        if self.ip_block is not None:
            return f"ipBlock {self.ip_block.cidr}"
        parts = []
        if self.namespace_selector is not None:
            parts.append(f"namespaces[{self.namespace_selector.describe()}]")
        if self.pod_selector is not None:
            parts.append(f"pods[{self.pod_selector.describe()}]")
        return " & ".join(parts) or "(empty peer)"


class PolicyPort(BaseModel):
    model_config = ConfigDict(frozen=True)

    protocol: Literal["TCP", "UDP", "SCTP"] = "TCP"
    port: int | str | None = None  # None = all ports of the protocol
    end_port: int | None = None

    def to_k8s(self) -> dict:
        out: dict = {"protocol": self.protocol}
        if self.port is not None:
            out["port"] = self.port
        if self.end_port is not None:
            out["endPort"] = self.end_port
        return out

    def describe(self) -> str:
        if self.port is None:
            return f"{self.protocol}/*"
        if self.end_port is not None:
            return f"{self.protocol}/{self.port}-{self.end_port}"
        return f"{self.protocol}/{self.port}"


class PolicyRule(BaseModel):
    """An ingress or egress rule. Empty ``peers``/``ports`` mean "all"."""

    model_config = ConfigDict(frozen=True)

    peers: tuple[PolicyPeer, ...] = ()
    ports: tuple[PolicyPort, ...] = ()

    def to_k8s(self, direction: Direction) -> dict:
        out: dict = {}
        if self.peers:
            out["from" if direction == Direction.INGRESS else "to"] = [
                p.to_k8s() for p in self.peers
            ]
        if self.ports:
            out["ports"] = [p.to_k8s() for p in self.ports]
        return out


class NetworkPolicy(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    namespace: str
    pod_selector: LabelSelector
    policy_types: tuple[Direction, ...]
    ingress: tuple[PolicyRule, ...] = ()
    egress: tuple[PolicyRule, ...] = ()
    labels: tuple[tuple[str, str], ...] = ()
    annotations: tuple[tuple[str, str], ...] = ()
    source: SourceRef = Field(default_factory=SourceRef)

    @property
    def id(self) -> str:
        return f"{self.namespace}/{self.name}"

    def rules(self, direction: Direction) -> tuple[PolicyRule, ...]:
        return self.ingress if direction == Direction.INGRESS else self.egress

    def applies_to(self, direction: Direction) -> bool:
        return direction in self.policy_types

    def to_k8s(self) -> dict:
        metadata: dict = {"name": self.name, "namespace": self.namespace}
        if self.labels:
            metadata["labels"] = dict(self.labels)
        if self.annotations:
            metadata["annotations"] = dict(self.annotations)
        spec: dict = {
            "podSelector": self.pod_selector.to_k8s(),
            "policyTypes": [str(t) for t in self.policy_types],
        }
        if Direction.INGRESS in self.policy_types:
            spec["ingress"] = [r.to_k8s(Direction.INGRESS) for r in self.ingress]
        if Direction.EGRESS in self.policy_types:
            spec["egress"] = [r.to_k8s(Direction.EGRESS) for r in self.egress]
        return {
            "apiVersion": "networking.k8s.io/v1",
            "kind": "NetworkPolicy",
            "metadata": metadata,
            "spec": spec,
        }


class ContainerPort(BaseModel):
    model_config = ConfigDict(frozen=True)

    container_port: int
    name: str | None = None
    protocol: Literal["TCP", "UDP", "SCTP"] = "TCP"


class Workload(BaseModel):
    """A set of identically-labelled pods (Deployment template, Pod, ...)."""

    model_config = ConfigDict(frozen=True)

    kind: str
    name: str
    namespace: str
    labels: tuple[tuple[str, str], ...]
    ports: tuple[ContainerPort, ...] = ()
    host_network: bool = False
    annotations: tuple[tuple[str, str], ...] = ()
    source: SourceRef = Field(default_factory=SourceRef)

    @property
    def id(self) -> str:
        return f"{self.namespace}/{self.name}"

    def labels_dict(self) -> dict[str, str]:
        return dict(self.labels)

    def tcp_ports(self) -> list[int]:
        return sorted({p.container_port for p in self.ports if p.protocol == "TCP"})

    def resolve_named_port(self, name: str, protocol: str = "TCP") -> int | None:
        for p in self.ports:
            if p.name == name and p.protocol == protocol:
                return p.container_port
        return None

    def port_name(self, number: int, protocol: str = "TCP") -> str | None:
        for p in self.ports:
            if p.container_port == number and p.protocol == protocol:
                return p.name
        return None


class ServicePort(BaseModel):
    model_config = ConfigDict(frozen=True)

    port: int
    target_port: int | str
    name: str | None = None
    protocol: Literal["TCP", "UDP", "SCTP"] = "TCP"


class Service(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    namespace: str
    selector: tuple[tuple[str, str], ...] | None
    ports: tuple[ServicePort, ...] = ()
    type: str = "ClusterIP"
    source: SourceRef = Field(default_factory=SourceRef)

    @property
    def id(self) -> str:
        return f"{self.namespace}/{self.name}"

    def selects(self, workload: Workload) -> bool:
        if self.selector is None or workload.namespace != self.namespace:
            return False
        labels = workload.labels_dict()
        return all(labels.get(k) == v for k, v in self.selector)


class Namespace(BaseModel):
    model_config = ConfigDict(frozen=True)

    name: str
    labels: tuple[tuple[str, str], ...]
    # False when the namespace is only referenced, never declared: its labels
    # (other than the automatic kubernetes.io/metadata.name) are unknown.
    labels_known: bool = True
    source: SourceRef = Field(default_factory=SourceRef)

    def labels_dict(self) -> dict[str, str]:
        return dict(self.labels)


class UnsupportedFeature(BaseModel):
    """Something present in the input that Clavure does not model."""

    model_config = ConfigDict(frozen=True)

    object_ref: str
    feature: str
    detail: str
    # Namespaces whose verdicts may be influenced; ("*",) for cluster scope;
    # () when the feature is informational only.
    affected_namespaces: tuple[str, ...] = ()
    source: SourceRef = Field(default_factory=SourceRef)


class Inventory(BaseModel):
    """Everything parsed from one set of manifests (or the live cluster)."""

    namespaces: dict[str, Namespace] = Field(default_factory=dict)
    workloads: dict[str, Workload] = Field(default_factory=dict)
    services: dict[str, Service] = Field(default_factory=dict)
    policies: dict[str, NetworkPolicy] = Field(default_factory=dict)
    unsupported: list[UnsupportedFeature] = Field(default_factory=list)
    ignored_kinds: dict[str, int] = Field(default_factory=dict)
    sources: list[str] = Field(default_factory=list)

    def with_policies(self, policies: dict[str, NetworkPolicy]) -> Inventory:
        return self.model_copy(update={"policies": dict(policies)})

    def namespace(self, name: str) -> Namespace:
        ns = self.namespaces.get(name)
        if ns is None:
            return Namespace(
                name=name,
                labels=(("kubernetes.io/metadata.name", name),),
                labels_known=False,
                source=SourceRef(origin="generated"),
            )
        return ns

    def services_for(self, workload: Workload) -> list[Service]:
        return [s for s in self.services.values() if s.selects(workload)]

    def backends(self, service: Service) -> list[Workload]:
        return [w for w in self.workloads.values() if service.selects(w)]
